---

- name: Run Cisco Nexus interface status
  cisco.nxos.nxos_command:
    commands:
      - show interface status
  register: show_int_status
  tags:
    - test

- name: Display interfaces status output
  ansible.builtin.debug:
    var: show_int_status.stdout_lines
  tags:
    - test
########################## Interfaces general commands ##########################
- name: interface description and shut/no shut
  cisco.nxos.nxos_interfaces:
    config:
      - name: Ethernet1/11
        description: by Ansible
        enabled: true  #administrative state of the interface (shut/no shut)
        mtu: 9216
        speed: 1000
        #mode: layer2
        mode: layer3  #no switchport
    state: merged  #default ansible state- means keep the existing configs and add this task to them
                    #replaced => only overrides the interface we mention
                    #overridden => Dangerous - overrides the mentioned interface and deletes all other interfaces
                    #gathered => just retrieve the config and do not do anything
                    #rendered => nothing sent to the switch- just check the playbook
  tags:
    - interface

- name: Delete or return interface parameters to default settings
  cisco.nxos.nxos_interfaces:
    config:
      - name: Ethernet1/10
    state: deleted  #means make the interface default
  tags:
    - default

- name: Gather interface configuration
  cisco.nxos.nxos_interfaces:
    state: gathered
  register: interface_result  #save the module result
  tags:
    - retrieve

- name: Display gathered interface configuration
  ansible.builtin.debug:
    var: interface_result.gathered
  tags:
    - retrieve

########################## Interfaces L2 commands ##########################
- name: Merge provided configuration with device configuration
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: Ethernet1/10
        trunk:
          allowed_vlans: 30  #if state: merged => will "add" vlan to existing allowed - if state:replaced => replace vlans
      - name: Ethernet1/11
        access:
          vlan: 30
    state: merged
  tags:
    - switchport

########################## Interfaces L3 commands ##########################
- name: Assign IPv4 address
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: Ethernet1/10
        ipv4:
          - address: 192.168.200.10/24
    state: merged
  tags:
    - ipv4

- name: Assign different IPv4 address per vPC-switch
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: Ethernet1/11
        ipv4:
          - address: "{{ interface_addresses[inventory_hostname] }}"
    state: merged
  vars:
    interface_addresses:
      sw5: 192.168.211.20/24
      sw6: 192.168.211.21/24
  tags:
    - ipv4-eth11

########################## VLAN commands ##########################
- name: Configure VLAN on the switch
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: 31
        name: ansible-vlan31
        enabled: true
        mode: ce          #default - classical ethernet - "fabricpath" is another option
        state: active     #default - "suspend" is another option
        #mapped_vni: 100  # (VNI) ID that is mapped to the VLAN
    state: merged         # deleted to delete the vlan
  tags:
    - vlan

- name: Delete vlans
  cisco.nxos.nxos_vlans:
    config:
      - vlan_id: 31
      #- vlan_id: 30
    state: deleted
  tags:
    - delete-vlan
#
- name: Gather vlans facts from the device using nxos_vlans
  cisco.nxos.nxos_vlans:
    state: gathered
  register: vlans
  tags:
    - gather-vlan

- name: Display gathered vlans
  ansible.builtin.debug:
    var: vlans.gathered
  tags:
    - gather-vlan


